FROM mcr.microsoft.com/playwright/python:v1.40.0-jammy

WORKDIR /app

RUN pip install --no-cache-dir aiogram==3.4.1
RUN playwright install chromium --with-deps

COPY main.py .

CMD ["python", "main.py"]
